In [1]:
from keras.models import Sequential# supervised
from keras.layers import Dense
import numpy as np

In [2]:
model=Sequential()
model.add(Dense(units=2,input_dim=2,activation='relu')) 
model.add(Dense(units=1,activation='sigmoid'))

In [4]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
print(model.summary())
print(model.get_weights())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None
[array([[ 0.6077728 , -0.21834826],
       [-0.03964341,  0.65608716]], dtype=float32), array([0., 0.], dtype=float32), array([[ 0.9690279],
       [-1.1592028]], dtype=float32), array([0.], dtype=float32)]


In [5]:
X=np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
print(X)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]


In [25]:
y=np.array([0.,1.,1.,0.])
y

array([0., 1., 1., 0.])

In [23]:
model.fit(X,y,epochs=150,batch_size=4)

Epoch 1/150
1/1 [==============================] - 0s 14ms/step - loss: 0.7060 - accuracy: 0.5000
Epoch 2/150
1/1 [==============================] - 0s 12ms/step - loss: 0.7057 - accuracy: 0.5000
Epoch 3/150
1/1 [==============================] - 0s 6ms/step - loss: 0.7053 - accuracy: 0.5000
Epoch 4/150
1/1 [==============================] - 0s 9ms/step - loss: 0.7050 - accuracy: 0.5000
Epoch 5/150
1/1 [==============================] - 0s 5ms/step - loss: 0.7046 - accuracy: 0.5000
Epoch 6/150
1/1 [==============================] - 0s 8ms/step - loss: 0.7043 - accuracy: 0.5000
Epoch 7/150
1/1 [==============================] - 0s 8ms/step - loss: 0.7039 - accuracy: 0.5000
Epoch 8/150
1/1 [==============================] - 0s 7ms/step - loss: 0.7036 - accuracy: 0.5000
Epoch 9/150
1/1 [==============================] - 0s 9ms/step - loss: 0.7033 - accuracy: 0.5000
Epoch 10/150
1/1 [==============================] - 0s 14ms/step - loss: 0.7029 - accuracy: 0.5000
Epoch 11/150
1/1 [========

1/1 [==============================] - 0s 12ms/step - loss: 0.6783 - accuracy: 0.5000
Epoch 85/150
1/1 [==============================] - 0s 11ms/step - loss: 0.6779 - accuracy: 0.5000
Epoch 86/150
1/1 [==============================] - 0s 11ms/step - loss: 0.6776 - accuracy: 0.5000
Epoch 87/150
1/1 [==============================] - 0s 7ms/step - loss: 0.6773 - accuracy: 0.5000
Epoch 88/150
1/1 [==============================] - 0s 9ms/step - loss: 0.6770 - accuracy: 0.5000
Epoch 89/150
1/1 [==============================] - 0s 7ms/step - loss: 0.6766 - accuracy: 0.5000
Epoch 90/150
1/1 [==============================] - 0s 4ms/step - loss: 0.6763 - accuracy: 0.5000
Epoch 91/150
1/1 [==============================] - 0s 9ms/step - loss: 0.6760 - accuracy: 0.5000
Epoch 92/150
1/1 [==============================] - 0s 6ms/step - loss: 0.6756 - accuracy: 0.5000
Epoch 93/150
1/1 [==============================] - 0s 12ms/step - loss: 0.6753 - accuracy: 0.5000
Epoch 94/150
1/1 [===========

In [10]:
print(model.get_weights())

[array([[ 0.5166231 , -0.12055355],
       [-0.13766275,  0.5632488 ]], dtype=float32), array([-0.09114985, -0.09283857], dtype=float32), array([[ 0.92149335],
       [-1.0699748 ]], dtype=float32), array([0.05433995], dtype=float32)]


In [15]:
y_pred=model.predict(X)
y_pred

1/1 [==============================] - 0s 17ms/step


array([[0.51358163],
       [0.38960162],
       [0.60978544],
       [0.4863078 ]], dtype=float32)

In [79]:
if y_pred.all() > 0.5:
    print(1)

1


In [21]:
print(vec2scalar(y_pred))

IndexError: list index out of range

In [22]:
print(vec2scalar(y_test))

NameError: name 'y_test' is not defined

# Perform multiclass classification on the wine data set using deep feed forward neural network

In [65]:
from sklearn.datasets import load_wine
import pandas as pd

In [66]:
data= load_wine()
x = pd.DataFrame(data.data,columns = data.feature_names)
y = pd.DataFrame(data.target,columns = ['Target'])
x

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [67]:
y

Target
0         0
1         0
2         0
3         0
4         0
..      ...
173       2
174       2
175       2
176       2
177       2

[178 rows x 1 columns]

In [68]:
from keras.utils import np_utils
encoded_Y=np_utils.to_categorical(y)
encoded_Y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [74]:
model=Sequential()
model.add(Dense(12,input_dim=13,activation='relu')) 
model.add(Dense(8,activation='relu'))
model.add(Dense(3,activation='softmax'))

In [75]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics='accuracy')

In [76]:
model.fit(x,encoded_Y,epochs=100,batch_size=10)

Epoch 1/100
18/18 [==============================] - 0s 2ms/step - loss: 312.1954 - accuracy: 0.2697
Epoch 2/100
18/18 [==============================] - 0s 2ms/step - loss: 238.6547 - accuracy: 0.2697
Epoch 3/100
18/18 [==============================] - 0s 2ms/step - loss: 179.7201 - accuracy: 0.2697
Epoch 4/100
18/18 [==============================] - 0s 3ms/step - loss: 137.0419 - accuracy: 0.2697
Epoch 5/100
18/18 [==============================] - 0s 4ms/step - loss: 103.2876 - accuracy: 0.2697
Epoch 6/100
18/18 [==============================] - 0s 3ms/step - loss: 78.4082 - accuracy: 0.2697
Epoch 7/100
18/18 [==============================] - 0s 2ms/step - loss: 58.2779 - accuracy: 0.2697
Epoch 8/100
18/18 [==============================] - 0s 2ms/step - loss: 44.1005 - accuracy: 0.2697
Epoch 9/100
18/18 [==============================] - 0s 4ms/step - loss: 32.1683 - accuracy: 0.2697
Epoch 10/100
18/18 [==============================] - 0s 3ms/step - loss: 23.6548 - accuracy: 0

18/18 [==============================] - 0s 4ms/step - loss: 0.5583 - accuracy: 0.8034
Epoch 83/100
18/18 [==============================] - 0s 2ms/step - loss: 0.5572 - accuracy: 0.7472
Epoch 84/100
18/18 [==============================] - 0s 2ms/step - loss: 0.5450 - accuracy: 0.7978
Epoch 85/100
18/18 [==============================] - 0s 2ms/step - loss: 0.5623 - accuracy: 0.8034
Epoch 86/100
18/18 [==============================] - 0s 2ms/step - loss: 0.5394 - accuracy: 0.7809
Epoch 87/100
18/18 [==============================] - 0s 2ms/step - loss: 0.5380 - accuracy: 0.7921
Epoch 88/100
18/18 [==============================] - 0s 2ms/step - loss: 0.5340 - accuracy: 0.7978
Epoch 89/100
18/18 [==============================] - 0s 2ms/step - loss: 0.5402 - accuracy: 0.7865
Epoch 90/100
18/18 [==============================] - 0s 939us/step - loss: 0.5277 - accuracy: 0.7978
Epoch 91/100
18/18 [==============================] - 0s 1ms/step - loss: 0.5381 - accuracy: 0.8034
Epoch 92/10

In [72]:
predictions=model.predict(x)

6/6 [==============================] - 0s 2ms/step


In [73]:
predictions

array([[2.01432392e-01, 4.44337457e-01, 3.54230106e-01],
       [9.99771774e-01, 6.59248644e-06, 2.21650029e-04],
       [9.99999285e-01, 1.85795912e-09, 7.45046520e-07],
       [1.00000000e+00, 1.06638077e-14, 1.66098801e-10],
       [1.15550108e-01, 5.51880240e-01, 3.32569599e-01],
       [1.00000000e+00, 3.74592189e-14, 3.98613725e-10],
       [1.00000000e+00, 2.73459776e-13, 1.59254165e-09],
       [9.99991655e-01, 5.93203815e-08, 8.32202932e-06],
       [9.99829412e-01, 4.35968832e-06, 1.66165715e-04],
       [9.99729455e-01, 8.39147560e-06, 2.62225891e-04],
       [1.00000000e+00, 1.14332929e-17, 1.41632843e-12],
       [1.00000000e+00, 3.26633685e-13, 1.80243276e-09],
       [1.00000000e+00, 1.07225424e-15, 3.35171717e-11],
       [9.99999881e-01, 1.90100033e-10, 1.52177762e-07],
       [1.00000000e+00, 4.02594310e-19, 1.37580553e-13],
       [9.99999762e-01, 4.03989897e-10, 2.57314156e-07],
       [9.99984384e-01, 1.44410635e-07, 1.54686986e-05],
       [9.97482121e-01, 1.92567